### PR TITLE
this is my personal information

### PR DESCRIPTION
**Pull request by akshay470**
sir you explained about github very well ,
we all understand it very well 
thank you so much for investing your valuable time.

### CODE REVIEW

**Comment by Sidharth-Singh10** [comment]
@akshay470 
please read `README.md` thoroughly.
You missed point 5.

**Comment by akshay470** [comment]
Sir can I upload PR again

**Comment by Sidharth-Singh10** [comment]
Yes, go ahead

**Comment by akshay470** [comment]
Thanks, I will.

**Comment by akshay470** [comment]
remote: Permission to 0PrashantYadav0/FOSS_AXIOS.git denied to akshay470.
fatal: unable to access 'https://github.com/0PrashantYadav0/FOSS_AXIOS.git/': The requested URL returned error: 403

@0PrashantYadav0 I am getting this error when I'm trying to push my profile code to the repo. Kindly look into it.

**Comment by Sidharth-Singh10** [comment]
@akshay470 , you have to clone your own forked repo. As we have instructed in the class.
You cloned Prashant's repo and trying to push changes into it. You dont have the authorization to do it.

**Comment by akshay470** [comment]
Ok, I will do that.

**Pull request closed without merging**
