### PR TITLE
Added my portfolio files - LCB2024045

### PR DESCRIPTION
**Pull request by sambhavgsharma**
_This pull request introduces a personal information webpage that includes the following:_

1. **index.html**: Contains basic information about me, such as my name, roll number, branch, skills, and hobbies.
2. **style.css**: Adds styling to the webpage, making it visually appealing with a responsive layout.
3. **Social Media Links**: LinkedIn, GitHub, and Instagram icons are included with hover effects, allowing users to connect with me through these platforms.
4. **Profile Picture**: I have inserted my profile picture in order to help people identify me.
5. **Video**  - A background video is used which is downloaded from open-source royalty video providers.
6. **Screen Recording** - Added screen_recording.mkv which contains the preview of my portfolio page

Thanks and Regards.

### CODE REVIEW

**Comment by 0PrashantYadav0** [comment]
Good work @sambhavgsharma and the description is also very nice just provide screenshot or video showing your profile.

**Comment by sambhavgsharma** [comment]
@0PrashantYadav0 I have added screen_recording.mkv as per your advice. Kindly inspect it.

**Comment by 0PrashantYadav0** [comment]
@sambhavgsharma you are supposed to put your screenshot here in comments

**Comment by sambhavgsharma** [comment]
https://github.com/user-attachments/assets/1ebd697b-5b13-4404-90a0-19de9530ba96

@0PrashantYadav0,I have added the attachment here. Please inspect it.

**Comment by 0PrashantYadav0** [comment]
@sambhavgsharma Good job and your description is also very good.

**Pull request merged**
