### PR TITLE
Added my portfolio files - LCB2024042

### PR DESCRIPTION
**Pull request by AbhinavNeema**
Please add my portfolio file
Name : Abhinav Neema
Roll No : LCB2024042

### CODE REVIEW

**Comment by 0PrashantYadav0** [comment]
@AbhinavNeema Provide screenshot of your html page

**Comment by AbhinavNeema** [comment]
Screenshot 2024-10-06 at 2 18 36 PM

**Comment by AbhinavNeema** [comment]
should I add this screenshot in pr ?
or it is ok

**Comment by 0PrashantYadav0** [comment]
Good work @AbhinavNeema

**Comment by AbhinavNeema** [comment]
Thank you sir @0PrashantYadav0

**Pull request merged**
