### PR TITLE
Added my portfolio files - LCI2024018

### PR DESCRIPTION
**Pull request by hasiniraja**

### CODE REVIEW

**Comment by 0PrashantYadav0** [comment]
@hasiniraja Provide screenshot of your html page

**Comment by hasiniraja** [comment]
[image: Screenshot 2024-10-05 153642.png]

**Comment by 0PrashantYadav0** [comment]
Your screenshot in not visible

**Comment by hasiniraja** [comment]
Sorry for that sir. Kindly check now..

**Pull request merged**
