### PR TITLE
Added my Portfolio files - LCI2024035

### PR DESCRIPTION
**Pull request by KuberTheGreat**
Prashant sir and Pratham sir explained the concepts of git and github fantastically. The class was pumped with energy, it was on fire!!!🔥🔥

### CODE REVIEW

**Comment by 0PrashantYadav0** [comment]
Thank you so much @KuberTheGreat . Just provide a screenshot of your html page

**Comment by KuberTheGreat** [comment]
Thank you @0PrashantYadav0 , I have added the screenshot of my profile, kindly inspect it.

**Comment by 0PrashantYadav0** [comment]
@KuberTheGreat remove .DS_Store file from main folder.

**Comment by KuberTheGreat** [comment]
@0PrashantYadav0 I have removed the .DS_Store file from the folders as instructed. Kindly check out the change.

**Comment by 0PrashantYadav0** [comment]
Good job @KuberTheGreat

**Pull request merged**
