### PR TITLE
Added my portfolio files- LCB2024021

### PR DESCRIPTION
**Pull request by vennelavarshini18**
Assignment done.

### CODE REVIEW

**Comment by 0PrashantYadav0** [comment]
@vennelavarshini18 Remove the txt file and provide a screenshot of your html page

**Comment by vennelavarshini18** [comment]
Sorry sir, but I don't know how to do that.
Can you please give steps?

**Comment by 0PrashantYadav0** [comment]
Just remove the file from your local machine and make a new commit. After that you can add that commit into this pr

**Comment by vennelavarshini18** [comment]
[image: image.png]

**Comment by 0PrashantYadav0** [comment]
Your screenshot in not visible

**Pull request merged**
