### PR TITLE
Added My Portfolio

### PR DESCRIPTION
**Pull request by charithaTubati**
INTRODUCTION

### CODE REVIEW

**Comment by 0PrashantYadav0** [comment]
@charithaTubati provide screenshot of your html page

**Comment by charithaTubati** [comment]
Screenshot 2024-10-05 203021
Screenshot 2024-10-05 203134
Screenshot 2024-10-05 203200

**Comment by 0PrashantYadav0** [comment]
i want the screenshot of your html page on browser that means i want to see how your web page look like.

**Comment by charithaTubati** [comment]
Screenshot 2024-10-05 224435

**Comment by 0PrashantYadav0** [comment]
@charithaTubati good work

**Pull request merged**
